### ISSUE TITLE
Gemspec depends on ffi-rzmq 0.7.0 not 0.9.0

### ISSUE THREAD

**Issue by halorgium** [chuckremes/zmqmachine#2]
The latest code has started to depend on features only contained within 0.9.0. 
I wasn't sure how you did your gemspec management.

**Comment by chuckremes** [comment]
Good point. That will be fixed in the next version.

Thanks!

**Comment by halorgium** [comment]
I believe you fixed this in 322423aaac994fed5b3594350bf5f0a524fb536f
