### ISSUE TITLE
Exceptions raised inside timer blocks cause timers not to be renewed

### ISSUE THREAD

**Issue by halorgium** [chuckremes/zmqmachine#5]
When two timers are running in the same reactor iteration and one of them raises an exception, neither timer is renewed. 

```
require 'zmqmachine'

counter = 0
handler = lambda do |exception|
  p [:exception, exception]
end

reactor = ZM::Reactor.new(:test, 10, exception_handler: handler)
reactor.run do
  reactor.periodical_timer 10 do
    p [:counter, counter]
    counter += 1
  end

  reactor.periodical_timer 100 do
    raise "Failed"
  end
end
reactor.join
```

I'm not sure what the expected behaviour is. 
Either way, the non-failing timer should be renewed.

**Comment by chuckremes** [comment]
Fixed by commit 6504f8eb85b91d3742dbcc82c17

Thanks for the bug report! I was working on an API change for Reactor, so this got pushed too as part of the bug fix. The version has been bumped to 0.7.0. I'll push a new gem this week.
